version: "3"

services:
  serverless_dynamo:
    container_name: serverless_dynamo
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    environment:
      AWS_REGION: ap-northeast-1 
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: access
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    networks:
      - serverless

  serverless_dynamo_admin:
    container_name: serverless_dynamo_admin
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    depends_on:
      - serverless_dynamo
    environment:
      DYNAMO_ENDPOINT: http://serverless_dynamo:8000
    networks:
      - serverless

networks:
  serverless:
    driver: bridge
