service: app

custom:
  serverless-offline:
    useDocker: true

plugins:
  - serverless-offline

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1
  environment:
    ENV: dev
    DYNAMO_HOST: http://serverless_dynamo:8000
    DYNAMO_REGION: ap-northeast-1
    AWS_ACCESS_KEY_ID: access 
    AWS_SECRET_ACCESS_KEY: access

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  hc:
    handler: bin/hc
    events:
      - httpApi:
          path: /hc
          method: get
  create_message:
    handler: bin/message/create
    events:
      - httpApi:
          path: /message
          method: post
  list_message:
    handler: bin/message/list
    events:
      - httpApi:
          path: /message
          method: get